module.exports = {
    binaryString: require('./src/binaryString'),
    bitwiseDifference: require('./src/bitwiseDifference'),
    bitwiseIntersection: require('./src/bitwiseIntersection'),
    bitwiseSubset: require('./src/bitwiseSubset'),
    bitwiseUnion: require('./src/bitwiseUnion'),
    checkBit: require('./src/checkBit'),
    clearBit: require('./src/clearBit'),
    countSetBits: require('./src/countSetBits'),
    fastGCD: require('./src/fastGCD'),
    fastModularExponentiation: require('./src/fastModularExponentiation'),
    fromBitmask: require('./src/fromBitmask'),
    generateCombinations: require('./src/generateCombinations'),
    generateSubsets: require('./src/generateSubsets'),
    grayCode: require('./src/grayCode'),
    hammingWeight: require('./src/hammingWeight'),
    highestSetBit: require('./src/highestSetBit'),
    isPowerOfTwo: require('./src/isPowerOfTwo'),
    logBase2: require('./src/logBase2'),
    lowestSetBit: require('./src/lowestSetBit'),
    nextBitPermutation: require('./src/nextBitPermutation'),
    popCountParallel: require('./src/popCountParallel'),
    setBit: require('./src/setBit'),
    toBitmask: require('./src/toBitmask'),
    toggleBit: require('./src/toggleBit')
};
